dist: trusty
sudo: false
language: rust
cache:
  - cargo: true
branches:
  only:
    - master
script:
  - cargo update
  - cargo build
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: beta
      before_script:
        - rustup component add rustfmt-preview clippy-preview
      script: >-
        cargo update &&
        cargo fmt -- --check &&
        cargo clippy --all-features --all-targets &&
        cargo test &&
        cargo test --all-features &&
        cargo test --no-default-features

    # FIXME: enable after releasing 1.30.0
    # - rust: 1.30.0
    # - rust: beta
    - rust: nightly

    # FIXME: switch to stable
    - rust: beta
      env: DEPLOY_API_DOC
      script: >-
        rm -rf target/doc &&
        cargo update &&
        cargo doc --all-features --no-deps &&
        rm -rf target/doc/.lock &&
        (echo '<meta http-equiv="refresh" content="0;URL=tsukuyomi_session/index.html">' > target/doc/index.html)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: tsukuyomi-rs/tsukuyomi-session
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
