(function() {var implementors = {};
implementors["tsukuyomi_session"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tsukuyomi_session/struct.Session.html\" title=\"struct tsukuyomi_session::Session\">Session</a>",synthetic:true,types:["tsukuyomi_session::session::Session"]},{text:"impl&lt;B&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tsukuyomi_session/struct.Storage.html\" title=\"struct tsukuyomi_session::Storage\">Storage</a>&lt;B&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;B: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,&nbsp;</span>",synthetic:true,types:["tsukuyomi_session::session::Storage"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tsukuyomi_session/backend/struct.CookieSessionBackend.html\" title=\"struct tsukuyomi_session::backend::CookieSessionBackend\">CookieSessionBackend</a>",synthetic:true,types:["tsukuyomi_session::backend::cookie::CookieSessionBackend"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"tsukuyomi_session/backend/struct.RedisSessionBackend.html\" title=\"struct tsukuyomi_session::backend::RedisSessionBackend\">RedisSessionBackend</a>",synthetic:true,types:["tsukuyomi_session::backend::redis::RedisSessionBackend"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
